import React from "react";
import { Composition } from "remotion";
import { Clip, type ClipSpec } from "./Clip";
import cuts from "../cuts.json";

const FPS = 30;

/**
 * One composition per clip per aspect. The cut list (cuts.json) is generated by launch/cut.mjs from the
 * recorder's marks and the voice track lengths; nothing here is hand-timed.
 */
export const Root: React.FC = () => {
  const specs = cuts as ClipSpec[];
  return (
    <>
      {specs.map((c) => (
        <Composition
          key={c.id}
          id={c.id}
          component={Clip}
          durationInFrames={Math.max(FPS, Math.round(c.duration * FPS))}
          fps={FPS}
          width={c.width}
          height={c.height}
          defaultProps={c}
        />
      ))}
    </>
  );
};
