// The Vercel build command. On production builds with a CONVEX_DEPLOY_KEY, it deploys the Convex
// backend and builds the site in one atomic step, so a merged room function goes live with the page
// that calls it. Without the key (previews, forks, or before the key is set) it is plain `pnpm build`.
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const isProd = process.env.VERCEL_ENV === "production";
const key = process.env.CONVEX_DEPLOY_KEY;
// The build's own commit, stamped into the bundle and published as /version.json, so an open tab can
// tell when a change has landed and offer a reload (the wall's data is live; its code needs a refresh).
const sha = process.env.VERCEL_GIT_COMMIT_SHA || spawnSync("git", ["rev-parse", "HEAD"]).stdout?.toString().trim() || "";
if (sha) process.env.VITE_BUILD_SHA = sha;

const run = (cmd, args) => {
  const r = spawnSync(cmd, args, { stdio: "inherit", env: process.env });
  if (r.status !== 0) process.exit(r.status ?? 1);
};

if (isProd && key) {
  console.log("[vercel-build] production + CONVEX_DEPLOY_KEY: deploying Convex, then building the site");
  run("npx", ["convex", "deploy", "--cmd", "pnpm build", "-y"]);
} else {
  console.log(`[vercel-build] ${isProd ? "production without CONVEX_DEPLOY_KEY" : "preview"}: building the site only`);
  run("pnpm", ["build"]);
}

try {
  writeFileSync("dist/version.json", JSON.stringify({ sha, at: Date.now() }));
  console.log(`[vercel-build] wrote dist/version.json (${sha.slice(0, 7) || "no sha"})`);
} catch (e) {
  console.warn("[vercel-build] could not write version.json:", e instanceof Error ? e.message : e);
}

// The share page (api/share.ts) returns the app's own HTML with per-change preview tags injected.
// Inline the built index.html so it never has to fetch itself (Deployment Protection would 401 on previews).
try {
  const html = readFileSync("dist/index.html", "utf8");
  writeFileSync("api/_index.ts", `// generated by scripts/vercel-build.mjs at build time; the committed file is a placeholder\nexport const INDEX_HTML = ${JSON.stringify(html)};\n`);
  console.log("[vercel-build] inlined dist/index.html into api/_index.ts");
} catch (e) {
  console.warn("[vercel-build] could not inline index.html:", e instanceof Error ? e.message : e);
}
