/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForYourSiteRouteImport } from './routes/for-your-site'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelapseRouteImport } from './routes/timelapse'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as RRoomSlugRouteImport } from './routes/r.$room.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYourSiteRoute = ForYourSiteRouteImport.update({
  id: '/for-your-site',
  path: '/for-your-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelapseRoute = TimelapseRouteImport.update({
  id: '/timelapse',
  path: '/timelapse',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomSlugRoute = RRoomSlugRouteImport.update({
  id: '/r/$room/$slug',
  path: '/r/$room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/for-your-site': typeof ForYourSiteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sites': typeof SitesRoute
  '/terms': typeof TermsRoute
  '/timelapse': typeof TimelapseRoute
  '/c/$id': typeof CIdRoute
  '/lab/$id': typeof LabIdRoute
  '/p/$id': typeof PIdRoute
  '/r/$room/$slug': typeof RRoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/for-your-site': typeof ForYourSiteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sites': typeof SitesRoute
  '/terms': typeof TermsRoute
  '/timelapse': typeof TimelapseRoute
  '/c/$id': typeof CIdRoute
  '/lab/$id': typeof LabIdRoute
  '/p/$id': typeof PIdRoute
  '/r/$room/$slug': typeof RRoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/for-your-site': typeof ForYourSiteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sites': typeof SitesRoute
  '/terms': typeof TermsRoute
  '/timelapse': typeof TimelapseRoute
  '/c/$id': typeof CIdRoute
  '/lab/$id': typeof LabIdRoute
  '/p/$id': typeof PIdRoute
  '/r/$room/$slug': typeof RRoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/for-your-site'
    | '/leaderboard'
    | '/privacy'
    | '/rules'
    | '/sites'
    | '/terms'
    | '/timelapse'
    | '/c/$id'
    | '/lab/$id'
    | '/p/$id'
    | '/r/$room/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/for-your-site'
    | '/leaderboard'
    | '/privacy'
    | '/rules'
    | '/sites'
    | '/terms'
    | '/timelapse'
    | '/c/$id'
    | '/lab/$id'
    | '/p/$id'
    | '/r/$room/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/for-your-site'
    | '/leaderboard'
    | '/privacy'
    | '/rules'
    | '/sites'
    | '/terms'
    | '/timelapse'
    | '/c/$id'
    | '/lab/$id'
    | '/p/$id'
    | '/r/$room/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  ForYourSiteRoute: typeof ForYourSiteRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  SitesRoute: typeof SitesRoute
  TermsRoute: typeof TermsRoute
  TimelapseRoute: typeof TimelapseRoute
  CIdRoute: typeof CIdRoute
  LabIdRoute: typeof LabIdRoute
  PIdRoute: typeof PIdRoute
  RRoomSlugRoute: typeof RRoomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-your-site': {
      id: '/for-your-site'
      path: '/for-your-site'
      fullPath: '/for-your-site'
      preLoaderRoute: typeof ForYourSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timelapse': {
      id: '/timelapse'
      path: '/timelapse'
      fullPath: '/timelapse'
      preLoaderRoute: typeof TimelapseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$room/$slug': {
      id: '/r/$room/$slug'
      path: '/r/$room/$slug'
      fullPath: '/r/$room/$slug'
      preLoaderRoute: typeof RRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  ForYourSiteRoute: ForYourSiteRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  SitesRoute: SitesRoute,
  TermsRoute: TermsRoute,
  TimelapseRoute: TimelapseRoute,
  CIdRoute: CIdRoute,
  LabIdRoute: LabIdRoute,
  PIdRoute: PIdRoute,
  RRoomSlugRoute: RRoomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
